version: "2.1"

volumes:
  certs:

services:
  # https://hub.docker.com/_/traefik/
  traefik:
    build: .
    environment: 
      CERTRESOLVER: "staging"
      IP_ALLOWLIST: "'0.0.0.0/0'"
      WHOAMI_HOST: "whoami.localhost"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8080:8080/tcp"
    volumes:
      - "certs:/var/certs"
    labels:
      io.balena.features.balena-socket: true

  whoami:
    image: "containous/whoami"
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.entrypoints: "websecure"
      traefik.http.routers.whoami.middlewares: "hsts-header@file,ip-allowlist@file"