[global]
checkNewVersion = false
sendAnonymousUsage = false

[log]
level = "INFO"

[api]
insecure = true

[entryPoints]

[entryPoints.web]
address = ":80"

[entryPoints.web.http]

[entryPoints.web.http.redirections]

[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"

[entryPoints.websecure]
address = ":443"

[certificatesResolvers.staging.acme]
email = "$ACME_EMAIL"
storage = "/var/certs/acme-staging.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[certificatesResolvers.staging.acme.tlsChallenge]

[certificatesResolvers.prod.acme]
email = "$ACME_EMAIL"
storage = "/var/certs/acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"

[certificatesResolvers.prod.acme.tlsChallenge]

[providers.file]
directory = "/etc/traefik/conf.d"
watch = true

[providers.docker]
endpoint = "unix:///var/run/balena.sock"
exposedByDefault = false
defaultRule = "Host(`$WHOAMI_HOST`)"
