# to enable this proxy service set the following environment variables
# either via docker-compose.yml or the Balena Application Dashboard
#
#  [BOOKSTACK_HOST]
#   public domain or subdomain with dns A records pointing to your server or firewall
#   example: bookstack.example.com
#
#  [BOOKSTACK_SERVER]
#   internal http server url to receive proxied traffic
#   example: http://192.168.8.5:80
#
[http]

[http.routers]

[http.routers.to-bookstack]
rule = "Host(`$BOOKSTACK_HOST`)"
service = "bookstack"
middlewares = ["hsts-header", "ip-allowlist"]

[http.routers.to-bookstack.tls]
certresolver = "$CERTRESOLVER"

[http.services]

[http.services.bookstack.loadBalancer]

[[http.services.bookstack.loadBalancer.servers]]
url = "$BOOKSTACK_SERVER"
