[http]

[http.routers]

[http.routers.to-homeassistant]
rule = "Host(`$HOMEASSISTANT_HOST`)"
service = "homeassistant"
middlewares = ["hsts-header"]

[http.routers.to-homeassistant.tls]
certresolver = "$CERTRESOLVER"

[http.services]

[http.services.homeassistant.loadBalancer]

[[http.services.homeassistant.loadBalancer.servers]]
url = "$HOMEASSISTANT_SERVER"
