# to enable this proxy service the following environment variables are required:
# HOMEASSISTANT_HOST (eg. homeassistant.example.com)
# HOMEASSISTANT_SERVER (eg. http://192.168.8.6:8123)

[http]

[http.routers]

[http.routers.to-homeassistant]
rule = "Host(`$HOMEASSISTANT_HOST`)"
service = "homeassistant"
middlewares = ["hsts-header"]

[http.services]

[http.services.homeassistant.loadBalancer]

[[http.services.homeassistant.loadBalancer.servers]]
url = "$HOMEASSISTANT_SERVER"
