# to enable this proxy service set the following environment variables
# either via docker-compose.yml or the Balena Application Dashboard
#
#  [NETDATA_HOST]
#   public domain or subdomain with dns A records pointing to your server or firewall
#   example: netdata.example.com
#
#  [NETDATA_SERVER]
#   internal http server url to receive proxied traffic
#   example: http://192.168.8.64:19999
#
[http]

[http.routers]

[http.routers.to-netdata]
rule = "Host(`$NETDATA_HOST`)"
service = "netdata"
middlewares = ["hsts-header", "basic-auth", "ip-allowlist"]

[http.routers.to-netdata.tls]
certresolver = "$CERTRESOLVER"

[http.services]

[http.services.netdata.loadBalancer]

[[http.services.netdata.loadBalancer.servers]]
url = "$NETDATA_SERVER"
