[http]

[http.routers]

[http.routers.to-nextcloud]
rule = "Host(`nextcloud.ACME_DOMAIN`)"
service = "nextcloud"
middlewares = ["secureheaders", "cardcaldav"]

[http.services]

[http.services.nextcloud.loadBalancer]

[[http.services.nextcloud.loadBalancer.servers]]
url = "http://192.168.8.6"

[http.middlewares]

[http.middlewares.cardcaldav.replacePathRegex]
regex = "^/.well-known/(card|cal)dav"
replacement = "/remote.php/dav/"
