[http]

[http.routers]

[http.routers.to-nextcloud]
rule = "Host(`nextcloud.ACME_DOMAIN`)"
service = "nextcloud"
middlewares = ["hsts-header", "cardcaldav"]

# change the certresolver from 'staging' to 'prod'
# once you're sure everything is working
[http.routers.to-nextcloud.tls]
certresolver = "staging"

[http.services]

[http.services.nextcloud.loadBalancer]

[[http.services.nextcloud.loadBalancer.servers]]
url = "http://192.168.8.6"

[http.middlewares]

[http.middlewares.cardcaldav.replacePathRegex]
regex = "^/.well-known/(card|cal)dav"
replacement = "/remote.php/dav/"
