# to enable this proxy service the following environment variables are required:
# NEXTCLOUD_HOST (eg. nextcloud.example.com)
# NEXTCLOUD_SERVER (eg. http://192.168.8.7:80)

[http]

[http.routers]

[http.routers.to-nextcloud]
rule = "Host(`$NEXTCLOUD_HOST`)"
service = "nextcloud"
middlewares = ["hsts-header", "cardcaldav"]

[http.services]

[http.services.nextcloud.loadBalancer]

[[http.services.nextcloud.loadBalancer.servers]]
url = "$NEXTCLOUD_SERVER"

[http.middlewares]

[http.middlewares.cardcaldav.replacePathRegex]
regex = "^/.well-known/(card|cal)dav"
replacement = "/remote.php/dav/"
