[http]

[http.routers]

[http.routers.to-nextcloud]
rule = "Host(`$NEXTCLOUD_HOST`)"
service = "nextcloud"
middlewares = ["hsts-header", "cardcaldav"]

# [http.routers.to-nextcloud.tls]
# certresolver = "prod"

[http.services]

[http.services.nextcloud.loadBalancer]

[[http.services.nextcloud.loadBalancer.servers]]
url = "$NEXTCLOUD_SERVER"

[http.middlewares]

[http.middlewares.cardcaldav.replacePathRegex]
regex = "^/.well-known/(card|cal)dav"
replacement = "/remote.php/dav/"
