# to enable this proxy service set the following environment variables
# either via docker-compose.yml or the Balena Application Dashboard
#
#  [NEXTCLOUD_HOST]
#   public domain or subdomain with dns A records pointing to your server or firewall
#   example: nextcloud.example.com
#
#  [NEXTCLOUD_SERVER]
#   internal http server url to receive proxied traffic
#   example: http://192.168.8.7:80
#
[http]

[http.routers]

[http.routers.to-nextcloud]
rule = "Host(`$NEXTCLOUD_HOST`)"
service = "nextcloud"
middlewares = ["hsts-header", "ip-allowlist", "cardcaldav"]

[http.routers.to-nextcloud.tls]
certresolver = "$CERTRESOLVER"

[http.services]

[http.services.nextcloud.loadBalancer]

[[http.services.nextcloud.loadBalancer.servers]]
url = "$NEXTCLOUD_SERVER"

[http.middlewares]

[http.middlewares.cardcaldav.replacePathRegex]
regex = "^/.well-known/(card|cal)dav"
replacement = "/remote.php/dav/"
