# to enable this proxy service set the following environment variables
# either via docker-compose.yml or the Balena Application Dashboard
#
#  [NZBGET_HOST]
#   public domain or subdomain with dns A records pointing to your server or firewall
#   example: nzbget.example.com
#
#  [NZBGET_SERVER]
#   internal http server url to receive proxied traffic
#   example: http://192.168.8.64:6789
#
[http]

[http.routers]

[http.routers.to-nzbget]
rule = "Host(`$NZBGET_HOST`)"
service = "nzbget"
middlewares = ["hsts-header", "basic-auth", "ip-allowlist"]

[http.routers.to-nzbget.tls]
certresolver = "$CERTRESOLVER"

[http.routers.to-nzbget-api]
rule = "Host(`${NZBGET_HOST}`) && PathPrefix(`/{jsonrpc:(/[^/:]*:[^/:]*)?/jsonrpc}`,`/{xmlrpc:(/[^/:]*:[^/]*)?/xmlrpc}`)"
service = "nzbget"
middlewares = ["hsts-header", "ip-allowlist"]

[http.routers.to-nzbget-api.tls]
certresolver = "$CERTRESOLVER"

[http.services]

[http.services.nzbget.loadBalancer]

[[http.services.nzbget.loadBalancer.servers]]
url = "$NZBGET_SERVER"
