# to enable this proxy service the following environment variables are required:
# PLEX_HOST (eg. plex.example.com)
# PLEX_SERVER (eg. http://192.168.8.64:32400)

[http]

[http.routers]

[http.routers.to-plex]
rule = "Host(`$PLEX_HOST`)"
service = "plex"
middlewares = ["hsts-header"]

[http.services]

[http.services.plex.loadBalancer]

[[http.services.plex.loadBalancer.servers]]
url = "$PLEX_SERVER"
