# to enable this proxy service set the following environment variables
# either via docker-compose.yml or the Balena Application Dashboard
#
#  [RADARR_HOST]
#   public domain or subdomain with dns A records pointing to your server or firewall
#   example: radarr.example.com
#
#  [RADARR_SERVER]
#   internal http server url to receive proxied traffic
#   example: http://192.168.8.64:7878
#
[http]

[http.routers]

[http.routers.to-radarr]
rule = "Host(`$RADARR_HOST`)"
service = "radarr"
middlewares = ["hsts-header", "basic-auth", "ip-allowlist"]

[http.routers.to-radarr.tls]
certresolver = "$CERTRESOLVER"

[http.routers.to-radarr-api]
rule = "Host(`$RADARR_HOST`) && PathPrefix(`/api`)"
service = "radarr"
middlewares = ["hsts-header", "ip-allowlist"]

[http.routers.to-radarr-api.tls]
certresolver = "$CERTRESOLVER"

[http.services]

[http.services.radarr.loadBalancer]

[[http.services.radarr.loadBalancer.servers]]
url = "$RADARR_SERVER"
