[http]

[http.middlewares]

[http.middlewares.secureheaders.headers]
# stsSeconds = 15552000
# stsIncludeSubdomains = true
# stsPreload = true
frameDeny = true
sslForceHost = true
sslRedirect = true
browserXssFilter = true
contentTypeNosniff = true
forceSTSHeader = true
customFrameOptionsValue = "SAMEORIGIN"

[http.middlewares.secureheaders.headers.customResponseHeaders]
X-Robots-Tag = "none"
