[http]

[http.middlewares]

[http.middlewares.secureheaders.headers]
stsSeconds = 15552000
frameDeny = true
sslForceHost = true
sslRedirect = true
stsIncludeSubdomains = true
browserXssFilter = true
contentTypeNosniff = true
forceSTSHeader = true
stsPreload = true
customFrameOptionsValue = "SAMEORIGIN"

[http.middlewares.secureheaders.headers.customResponseHeaders]
X-Robots-Tag = "none"
