# to enable this proxy service set the following environment variables
# either via docker-compose.yml or the Balena Application Dashboard
#
#  [SONARR_HOST]
#   public domain or subdomain with dns A records pointing to your server or firewall
#   example: sonarr.example.com
#
#  [SONARR_SERVER]
#   internal http server url to receive proxied traffic
#   example: http://192.168.8.64:8989
#
[http]

[http.routers]

[http.routers.to-sonarr]
rule = "Host(`$SONARR_HOST`)"
service = "sonarr"
middlewares = ["hsts-header", "basic-auth", "ip-allowlist"]

[http.routers.to-sonarr.tls]
certresolver = "$CERTRESOLVER"

[http.routers.to-sonarr-api]
rule = "Host(`$SONARR_HOST`) && PathPrefix(`/api`)"
service = "sonarr"
middlewares = ["hsts-header", "ip-allowlist"]

[http.routers.to-sonarr-api.tls]
certresolver = "$CERTRESOLVER"

[http.services]

[http.services.sonarr.loadBalancer]

[[http.services.sonarr.loadBalancer.servers]]
url = "$SONARR_SERVER"
