# to enable this proxy service set the following environment variables
# either via docker-compose.yml or the Balena Application Dashboard
#
#  [ZONEMINDER_HOST]
#   public domain or subdomain with dns A records pointing to your server or firewall
#   example: zm.example.com
#
#  [ZONEMINDER_SERVER]
#   internal http server url to receive proxied traffic
#   example: http://192.168.8.3:80
#
[http]

[http.routers]

[http.routers.to-zoneminder]
rule = "Host(`$ZONEMINDER_HOST`)"
service = "zoneminder"
middlewares = ["hsts-header", "add-zm-prefix", "ip-allowlist"]

[http.routers.to-zoneminder.tls]
certresolver = "$CERTRESOLVER"

[http.services]

[http.services.zoneminder.loadBalancer]

[[http.services.zoneminder.loadBalancer.servers]]
url = "$ZONEMINDER_SERVER"

[http.middlewares]

[http.middlewares.add-zm-prefix.replacePathRegex]
regex = "^(/zm/)?(.*)"
replacement = "/zm/$2"
