[http]

[http.routers]

[http.routers.to-zoneminder]
rule = "Host(`zoneminder.ACME_DOMAIN`)"
service = "zoneminder"
middlewares = ["hsts-header", "add-zm-prefix"]

# change the certresolver from 'staging' to 'prod'
# once you're sure everything is working
[http.routers.to-zoneminder.tls]
certresolver = "staging"

[http.services]

[http.services.zoneminder.loadBalancer]

[[http.services.zoneminder.loadBalancer.servers]]
url = "http://192.168.8.7"

[http.middlewares]

[http.middlewares.add-zm-prefix.replacePathRegex]
regex = "^(/zm/)?(.*)"
replacement = "/zm/$2"
