[http]

[http.routers]

[http.routers.to-zoneminder]
rule = "Host(`$ZONEMINDER_HOST`)"
service = "zoneminder"
middlewares = ["hsts-header", "add-zm-prefix"]

[http.routers.to-zoneminder.tls]
certresolver = "$CERTRESOLVER"

[http.services]

[http.services.zoneminder.loadBalancer]

[[http.services.zoneminder.loadBalancer.servers]]
url = "$ZONEMINDER_SERVER"

[http.middlewares]

[http.middlewares.add-zm-prefix.replacePathRegex]
regex = "^(/zm/)?(.*)"
replacement = "/zm/$2"
