[http]

[http.routers]

[http.routers.to-zoneminder]
rule = "Host(`zoneminder.ACME_DOMAIN`)"
service = "zoneminder"
middlewares = ["hsts-header", "add-zm-prefix"]

# [http.routers.to-zoneminder.tls]
# certresolver = "prod"
[http.services]

[http.services.zoneminder.loadBalancer]

[[http.services.zoneminder.loadBalancer.servers]]
url = "http://zoneminder.lan"

[http.middlewares]

[http.middlewares.add-zm-prefix.replacePathRegex]
regex = "^(/zm/)?(.*)"
replacement = "/zm/$2"
